GET  https://exapi-gjsy.onrender.com/getinfo
###
POST https://exapi-gjsy.onrender.com/loginAuthe
Content-Type: application/json

 {
    "passwords":"123",
    "emails":"eric.bazirake@abr.rw"
 }

###
GET  https://exapi-gjsy.onrender.com/content
###
 POST https://exapi-gjsy.onrender.com/logout
###
GET https://exapi-gjsy.onrender.com/contentAuth/5
###
GET https://exapi-gjsy.onrender.com/detailAuth/16/2
###
GET  https://exapi-gjsy.onrender.com/detail/20/3
